
 
services:
  app:
    build: ./app
    ports:
      - 8000:8000  
    networks:
      - backend-network  
    depends_on:
      database:
        condition: service_healthy  
  database:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - C:/Users/Yosef/vsc_project/week10_compose/sql/init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "3306:3306"      
    environment:
      MYSQL_DATABASE: contacts_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST_NAME: 'localhost'
    networks:
      - backend-network  
    healthcheck:              
      test: ["CMD","mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 5       
      
 
volumes:
  mysql_data:                 # Creates a managed volume on the host

networks:
  backend-network:            # Creates a custom bridge network
    driver: bridge